LVGL_APP_SITE = $(BR2_EXTERNAL_IMX6ULL_APP_PATH)/package/lvgl-app/source
LVGL_APP_SITE_METHOD = local
LVGL_APP_DEPENDENCIES = host-pkgconf host-cmake
LVGL_APP_VERSION = 1.0.0

LVGL_APP_LICENSE = MIT
LVGL_APP_LICENSE_FILES = LICENSE

LVGL_APP_SUBDIR = .
LVGL_APP_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr

$(eval $(cmake-package))
